### ISSUE TITLE
Depricated getiterator()

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/dreqPy1.2#1]
I am busy to port our ece2cmor3 and genecec packages to (the latest) python3. If I am not mistaken, then I encounter with the latest python3 versions a problem with the dreqPy package which I did not have with an earlier python3 versions (say python3.4 or so). I think this is due to the depreciation of xlrd in the latest python3 versions. (In our own code we also have to replace xlrd by openpyxl.) I guess it is related to the fact that xlrd is deprecated as for example is mentioned [here](https://stackoverflow.com/questions/64264563/attributeerror-elementtree-object-has-no-attribute-getiterator-when-trying); maybe in dreqPy it is related to the engine='openpyxl' suggested option? I am not sure.

The easiest way to reproduce my error is:

python3 --version
Python 3.10.6

which python3
/usr/bin/python3

pip3 install dreqPy==01.0.33
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: dreqPy==01.0.33 in ./.local/lib/python3.10/site-packages (1.0.33)

python3
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dreqPy import dreq
>>> dq = dreq.loadDreq()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/reerink/.local/lib/python3.10/site-packages/dreqPy/dreq.py", line 1020, in __init__
    self.c = config( thisdoc=dreqXML, configdoc=configdoc, useShelve=useShelve,strings=strings,manifest=manifest,configOnly=configOnly,lxml=lxml)
  File "/home/reerink/.local/lib/python3.10/site-packages/dreqPy/dreq.py", line 581, in __init__
    self.__read__(d, c)
  File "/home/reerink/.local/lib/python3.10/site-packages/dreqPy/dreq.py", line 657, in __read__
    self.parent_map = dict((c, p) for p in root.getiterator() for c in p)
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'

I suppose I am using the latest dreqPy version in the correct way like this? If so, would it be possible to release a fix for this? I am relying with [genecec.py](https://github.com/EC-Earth/ece2cmor3/blob/master/ece2cmor3/scripts/genecec.py) on dreqPy in order to loop over all MIPs and all experiments (based on an example you provided me a few years ago), it's at the hart of our total framework for EC-Earth output.

**Comment by martinjuckes** [comment]
The problem is with a call to ElementTree from dreq.py. 

Fixed (for python3.10) by replacing `getiterator()` with `iter()`.

Need to check compatibility with other python versions.  Add to unittests?

**Comment by martinjuckes** [comment]
Now tested with `simpleCheck.py` on 2.7, 3.8 and 3.10.

System dependency xmllint,  python dependency xlsxwriter.

**Comment by treerink** [comment]
Hi Martin,
I have done the following:
```
git clone git@github.com:cmip6dr/dreqPy1.2.git
cd dreqPy1.2
python3 --version
Python 3.10.6

cd Package/dreqPy/
python3 ./simpleCheck.py
Required libraries present
Dreq software import checked: 01.02.00
Dreq sample load checked
Dreq links checked
Suite 1 (dreq module): All checks passed
WARNING[002]: failed to detect xmllint command line program
Optional checks omitted
WARNING[003]: failed to get version with command line call
WARNING[005]: failed to get volume est. with command line call: python3.10 dreqCmdl.py
Suite 2 (xmllint & command line): Errors detected
```
Is this the test you wanted me to do? This test is done on my Ubuntu 22.04 laptop.

Meanwhile I tested that indeed with python3.4 `getiterator()` still did work, for that I created a conda python3.4 & dreqPy environment:

with my `environment.yml` like this:
```
name: python34
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.4
  - dreqpy==01.00.33
```
but that is no surprise.

From this you can see that my usual way of using `dreqPy` is via conda.

**Comment by martinjuckes** [comment]
Hi Thomas, I can't replicate your error. I have python 3.10.8 on Ubuntu 20.04.

Can you update your copy and run `simpleCheck.py -V`. This should print the full error messages from the checks that fail.

**Comment by treerink** [comment]
After navigating to the `dreqPy1.2/Package/dreqPy/` directory:
```
python3 --version
Python 3.10.6

git pull
Already up to date.  # I did not get anything new?!

python3 ./simpleCheck.py -V
Required libraries present
Dreq software import checked: 01.02.00
Dreq sample load checked
Dreq links checked
Suite 1 (dreq module): All checks passed
WARNING[002]: failed to detect xmllint command line program
Optional checks omitted
WARNING[003]: failed to get version with command line call
WARNING[005]: failed to get volume est. with command line call: python3.10 ./dreqCmdl.py
Suite 2 (xmllint & command line): Errors detected
```
Because of the error I just tried `dreqCmdl.py` as well:
```
python3 ./dreqCmdl.py
No xlsxwrite: will not make tables ...
Traceback (most recent call last):
  File "/home/reerink/cmorize/test-dreq/dreqPy1.2/Package/dreqPy/./dreqCmdl.py", line 8, in <module>
    import scope
  File "/home/reerink/cmorize/test-dreq/dreqPy1.2/Package/dreqPy/scope.py", line 22, in <module>
    import volsum
  File "/home/reerink/cmorize/test-dreq/dreqPy1.2/Package/dreqPy/volsum.py", line 1, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'
```

Via a mamba environment in which I have python3.11.0 I tried with that latest python version:
```
${mambapath}/envs/ece2cmor3-python-3/bin/python3 --version
Python 3.11.0

${mambapath}/envs/ece2cmor3-python-3/bin/python3 ./simpleCheck.py -V
Required libraries present
Dreq software import checked: 01.02.00
Dreq sample load checked
Dreq links checked
Suite 1 (dreq module): All checks passed
WARNING[002]: failed to detect xmllint command line program
Optional checks omitted
WARNING[003]: failed to get version with command line call
WARNING[005]: failed to get volume est. with command line call: python3.11 ./dreqCmdl.py
Suite 2 (xmllint & command line): Errors detected
```
Giving the same warnings/error, still all on my Ubuntu 22.04 laptop.

**Comment by treerink** [comment]
I did no any install command sofar, so I tried this one:
```
cd ../
pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/reerink/cmorize/test-dreq/dreqPy1.2/Package
  Preparing metadata (setup.py) ... done
Installing collected packages: dreqPy
  Attempting uninstall: dreqPy
    Found existing installation: dreqPy 1.0.33
    Uninstalling dreqPy-1.0.33:
      Successfully uninstalled dreqPy-1.0.33
  Running setup.py develop for dreqPy
Successfully installed dreqPy-1.2.0
```
But still I get after
```
cd dreqPy
python3 ./simpleCheck.py -V
```
the same error.

**Comment by martinjuckes** [comment]
I'm sorry, I messed up with the last  commit. Can you try once more?

**Comment by treerink** [comment]
Hi Martin,

Thanks, yes now I got updates after my pull. Running again is more verbose indeed:
```
python3 --version
Python 3.10.6

python3 ./simpleCheck.py -V
Required libraries present
Dreq software import checked: 01.02.00
Dreq sample load checked
Dreq links checked
Suite 1 (dreq module): All checks passed
WARNING[002]: failed to detect xmllint command line program
Optional checks omitted
WARNING[003]: failed to get version with command line call
['Traceback (most recent call last):\n', '  File "/home/reerink/cmorize/test-dreq/dreqPy1.2/Package/dreqPy/./dreqCmdl.py", line 8, in <module>\n', '    import scope\n', '  File "/home/reerink/cmorize/test-dreq/dreqPy1.2/Package/dreqPy/scope.py", line 22, in <module>\n', '    import volsum\n', '  File "/home/reerink/cmorize/test-dreq/dreqPy1.2/Package/dreqPy/volsum.py", line 1, in <module>\n', '    import xlsxwriter\n', "ModuleNotFoundError: No module named 'xlsxwriter'\n"]
WARNING[005]: failed to get volume est. with command line call: python3.10 ./dreqCmdl.py
['Traceback (most recent call last):\n', '  File "/home/reerink/cmorize/test-dreq/dreqPy1.2/Package/dreqPy/./dreqCmdl.py", line 8, in <module>\n', '    import scope\n', '  File "/home/reerink/cmorize/test-dreq/dreqPy1.2/Package/dreqPy/scope.py", line 22, in <module>\n', '    import volsum\n', '  File "/home/reerink/cmorize/test-dreq/dreqPy1.2/Package/dreqPy/volsum.py", line 1, in <module>\n', '    import xlsxwriter\n', "ModuleNotFoundError: No module named 'xlsxwriter'\n"]
Suite 2 (xmllint & command line): Errors detected
```

**Comment by martinjuckes** [comment]
OK ... so you need to install `xlsxwriter` .

I intend to separate out the code that uses `xlsxwriter` to create a simpler, more portable, core. But, for now, can you add it to your conda environment?

**Comment by treerink** [comment]
Ok, I have created with mamba an environment which contains `python3.11.0` & `xlsxwriter` (I left out `dreqPy)`:
```
name: dreqPyenv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - xlsxwriter
```
After activating that environment and navigating to the `dreqPy1.2/Package/dreqPy/` directory, I have:
```
python3 --version
Python 3.11.0

python3 ./simpleCheck.py -V
Required libraries present
Dreq software import checked: 01.02.00
Dreq sample load checked
Dreq links checked
Suite 1 (dreq module): All checks passed
WARNING[002]: failed to detect xmllint command line program
Optional checks omitted
Suite 2 (xmllint & command line): Errors detected
ALL CHECK PASSED
```
Looks better, no idea about the _WARNING_ and _Errors detected_?

And ... how about getting dreqPy1.2 via the conda channel? That needs still to be built first I guess?

**Comment by martinjuckes** [comment]
`xmllint` is a Linux command line tool which checks the data request XML file against an XSD schema. The warning is telling you that it has not been found, which means that this conformance check is not possible. It does not affect the functionality of the python code. 

I can push the 1.2 version to pypi .. can conda access it from there?

**Comment by treerink** [comment]
Ok. I think so, and else I think it can be used via pip from there (but I am not an expert on this). Before I included `dreqPy` either like this:
```
dependencies:
  - dreqpy==01.00.33
```
or this
```
dependencies:
  - pip
  - pip:
    - dreqPy==01.00.33
```
How do I have to refer to the new one, like this:
```
dependencies:
  - dreqpy1.2==01.00.33
```
or
```
dependencies:
  - dreqpy==01.20.33
```
Do you know?

**Comment by martinjuckes** [comment]
I've put it into Pypi now .. it is version 1.2.0, so `dreqPy==01.2.0` should get it.

**Comment by treerink** [comment]
Hi Martin,

Thanks a lot, it is working now. Via pip it works:
```
name: dreqPyenv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - xlsxwriter
  - pip:
    - dreqPy==01.2.0
```
I have made the changes in our own code, and that is working again now as well.

Thanks again!
Thomas

**Comment by martinjuckes** [comment]
OK, thanks for raising it.I'll close this an open a new issue about cleaning up the error messages when xlsxwriter is missing.
